services:
  asearch:
    build: .
    container_name: asearch
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./src/
          target: /app/
        - action: rebuild
          path: pyproject.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.asearch.rule=Host(`asearch.gootman.ca`)
      - traefik.http.routers.asearch.entrypoints=websecure
